import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { User } from '../entity/user.entity';
import { UserDTO } from '../entity/user.dto';
import { UserService } from '../service/user.service';

@Controller('user')
@UseGuards(AuthGuard('jwt'))
export class UserController extends BasicRestController<User, string, UserDTO>{

    constructor(protected service: UserService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */