export class AmountDTO {
    readonly uuid: string;
    readonly value: Number;
    readonly cost: Number;
    readonly active: Number;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */