import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { RangeAmount } from 'src/api/range_amount/entity/range_amount.entity'

@Entity({name:'amount'})
export class Amount{

    @PrimaryGeneratedColumn()
    uuid: string;

    @Column()
    value: Number;

    @Column()
    cost: Number;

    @Column()
    active: Number;

    @OneToMany(() => RangeAmount, e => e.amount)
    ranges: RangeAmount[];

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */