import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { BankSupported } from '../entity/bank_supported.entity';
import { BankSupportedDTO } from '../entity/bank_supported.dto';
import { BankSupportedService } from '../service/bank_supported.service';

@Controller('bank-supported')
@UseGuards(AuthGuard('jwt'))
export class BankSupportedController extends BasicRestController<BankSupported, string, BankSupportedDTO>{

    constructor(protected service: BankSupportedService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */