import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Messages } from '../entity/messages.entity';
import { MessagesDTO } from '../entity/messages.dto';

@Injectable()
export class MessagesService extends BasicCrudService<Messages, string, MessagesDTO>{

    constructor(
        @InjectRepository(Messages)
        protected repo: Repository<Messages>,
    ) {super();}

    findById(id: string): Promise<Messages>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: MessagesDTO): Messages{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new Messages();
        entity.cod = dto.cod;
        entity.message = dto.message;
        return entity;
    }

    async dataValidationBeforeCreate(dto: MessagesDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: Messages, dto: MessagesDTO): Messages{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.message = dto.message ? dto.message : entity.message;
        return entity;
    }

    async dataValidationBeforeEdit(dto: MessagesDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */