import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AdvanceState } from './entity/advance_state.entity';
import { AdvanceStateService } from './service/advance_state.service';
import { AdvanceStateController } from './controller/advance_state.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([AdvanceState]),
    ],
    controllers: [
        AdvanceStateController,
    ],
    providers: [
        AdvanceStateService,
    ],
    exports: [
        AdvanceStateService,
    ],
})
export class AdvanceStateModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */