import { Advance } from 'src/api/advance/entity/advance.entity';
import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';

@Entity({name:'advance_period'})
export class AdvancePeriod{

    @PrimaryGeneratedColumn()
    uuid: string;

    @Column()
    name: string;

    @Column()
    created_date: Date;

    @Column()
    finished_date: Date;

    @Column()
    enterprise_id: number;

    @OneToMany(() => Advance, e => e.period)
    advances: Advance[];

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */