import { Bank } from 'src/api/bank/entity/bank.entity';
import { Entity, Column, PrimaryColumn, ManyToOne, JoinColumn } from 'typeorm';

@Entity({name:'bank_messages'})
export class BankMessages{

    @PrimaryColumn()
    cod: string;

    @Column()
    message: string;

    @ManyToOne(() => Bank, e => e.messages, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "bank" })
    bank: Bank;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */