import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Employee } from './entity/employee.entity';
import { EmployeeService } from './service/employee.service';
import { EmployeeController } from './controller/employee.controller';
import { EmployeeBusiness } from './service/employee.business';

@Module({
    imports: [
        TypeOrmModule.forFeature([Employee]),
    ],
    controllers: [
        EmployeeController,
    ],
    providers: [
        EmployeeService, EmployeeBusiness
    ],
    exports: [
        EmployeeService, EmployeeBusiness
    ],
})
export class EmployeeModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */