import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Messages } from '../entity/messages.entity';
import { MessagesDTO } from '../entity/messages.dto';
import { MessagesService } from '../service/messages.service';

@Controller('messages')
@UseGuards(AuthGuard('jwt'))
export class MessagesController extends BasicRestController<Messages, string, MessagesDTO>{

    constructor(protected service: MessagesService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */