import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { Employee } from 'src/api/employee/entity/employee.entity'
import { BankSupported } from 'src/api/bank_supported/entity/bank_supported.entity'

@Entity({name:'fintech'})
export class Fintech{

    @PrimaryColumn()
    cod: string;

    @Column()
    name: string;

    @OneToMany(() => Employee, e => e.fintech)
    employees: Employee[];
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */