import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Advance } from './entity/advance.entity';
import { AdvanceService } from './service/advance.service';
import { AdvanceController } from './controller/advance.controller';
import { AdvanceBusiness } from './service/advance.business';
import { EmployeeModule } from '../employee/employee.module';

@Module({
    imports: [
        TypeOrmModule.forFeature([Advance]),
        EmployeeModule,
    ],
    controllers: [
        AdvanceController,
    ],
    providers: [
        AdvanceService, AdvanceBusiness
    ],
    exports: [
        AdvanceService, AdvanceBusiness
    ],
})
export class AdvanceModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */