import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { RangeAmount } from './entity/range_amount.entity';
import { RangeAmountService } from './service/range_amount.service';
import { RangeAmountController } from './controller/range_amount.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([RangeAmount]),
    ],
    controllers: [
        RangeAmountController,
    ],
    providers: [
        RangeAmountService,
    ],
    exports: [
        RangeAmountService,
    ],
})
export class RangeAmountModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */