import { Entity, Column, PrimaryColumn } from 'typeorm';

@Entity({name:'messages'})
export class Messages{

    @PrimaryColumn()
    cod: string;

    @Column()
    message: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */