import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { Enterprise } from 'src/api/enterprise/entity/enterprise.entity'
import { Employee } from 'src/api/employee/entity/employee.entity'
import { Amount } from 'src/api/amount/entity/amount.entity';
import { RangeAmount } from 'src/api/range_amount/entity/range_amount.entity';

@Entity({name:'range'})
export class Range{

    @PrimaryGeneratedColumn()
    uuid: string;

    @Column()
    id: string;

    @Column()
    money_limit: number;

    @ManyToOne(() => Enterprise, e => e.ranges, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "enterprise" })
    enterprise: Enterprise;

    @OneToMany(() => Amount, e => e.range)
    amounts: Amount[];

    @OneToMany(() => Employee, e => e.range)
    employees: Employee[];

    @OneToMany(() => RangeAmount, e => e.range)
    amountsRanges: RangeAmount[];


}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */