export class RangeDTO {
    readonly uuid: string;
    readonly id: string;
    readonly enterprise: number;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */