import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Range } from '../entity/range.entity';
import { RangeDTO } from '../entity/range.dto';
import { RangeService } from '../service/range.service';

@Controller('range')
export class RangeController extends BasicRestController<Range, string, RangeDTO>{

    constructor(protected service: RangeService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */