import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { UserRol } from '../entity/user_rol.entity';
import { UserRolDTO } from '../entity/user_rol.dto';

@Injectable()
export class UserRolService extends BasicCrudService<UserRol, string, UserRolDTO>{

    constructor(
        @InjectRepository(UserRol)
        protected repo: Repository<UserRol>,
    ) {super();}

    findById(id: string): Promise<UserRol>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: UserRolDTO): UserRol{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new UserRol();
        entity.name = dto.name;
        return entity;
    }

    async dataValidationBeforeCreate(dto: UserRolDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: UserRol, dto: UserRolDTO): UserRol{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        return entity;
    }

    async dataValidationBeforeEdit(dto: UserRolDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */