import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { AdvanceState } from '../entity/advance_state.entity';
import { AdvanceStateDTO } from '../entity/advance_state.dto';

@Injectable()
export class AdvanceStateService extends BasicCrudService<AdvanceState, string, AdvanceStateDTO>{

    constructor(
        @InjectRepository(AdvanceState)
        protected repo: Repository<AdvanceState>,
    ) {super();}

    findById(id: string): Promise<AdvanceState>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: AdvanceStateDTO): AdvanceState{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new AdvanceState();
        entity.name = dto.name;
        return entity;
    }

    async dataValidationBeforeCreate(dto: AdvanceStateDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: AdvanceState, dto: AdvanceStateDTO): AdvanceState{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        return entity;
    }

    async dataValidationBeforeEdit(dto: AdvanceStateDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */