import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Messages } from './entity/messages.entity';
import { MessagesService } from './service/messages.service';
import { MessagesController } from './controller/messages.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([Messages]),
    ],
    controllers: [
        MessagesController,
    ],
    providers: [
        MessagesService,
    ],
    exports: [
        MessagesService,
    ],
})
export class MessagesModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */