import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Enterprise } from '../entity/enterprise.entity';
import { EnterpriseDTO } from '../entity/enterprise.dto';
import { EnterpriseService } from '../service/enterprise.service';

@Controller('enterprise')
@UseGuards(AuthGuard('jwt'))
export class EnterpriseController extends BasicRestController<Enterprise, number, EnterpriseDTO>{

    constructor(protected service: EnterpriseService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */