import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { BankAccountType } from '../entity/bank_account_type.entity';
import { BankAccountTypeDTO } from '../entity/bank_account_type.dto';
import { BankAccountTypeService } from '../service/bank_account_type.service';

@Controller('bank-account-type')
@UseGuards(AuthGuard('jwt'))
export class BankAccountTypeController extends BasicRestController<BankAccountType, string, BankAccountTypeDTO>{

    constructor(protected service: BankAccountTypeService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */