import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { User } from 'src/api/user/entity/user.entity'
import { Range } from 'src/api/range/entity/range.entity'

@Entity({name:'enterprise'})
export class Enterprise{

    @PrimaryGeneratedColumn('increment')
    id: number;

    @Column()
    nit: string;

    @Column()
    name: string;

    @Column()
    address: string;

    @Column()
    date_limit: Date;

    @OneToMany(() => User, e => e.enterprise)
    users: User[];

    @OneToMany(() => Range, e => e.enterprise)
    ranges: Range[];

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */