export class EnterpriseDTO {
    readonly id: number;
    readonly nit: string;
    readonly name: string;
    readonly address: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */