import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { BankSupported } from './entity/bank_supported.entity';
import { BankSupportedService } from './service/bank_supported.service';
import { BankSupportedController } from './controller/bank_supported.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([BankSupported]),
    ],
    controllers: [
        BankSupportedController,
    ],
    providers: [
        BankSupportedService,
    ],
    exports: [
        BankSupportedService,
    ],
})
export class BankSupportedModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */