import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Fintech } from './entity/fintech.entity';
import { FintechService } from './service/fintech.service';
import { FintechController } from './controller/fintech.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([Fintech]),
    ],
    controllers: [
        FintechController,
    ],
    providers: [
        FintechService,
    ],
    exports: [
        FintechService,
    ],
})
export class FintechModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */