import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Range } from '../entity/range.entity';
import { RangeService } from './range.service';

@Injectable()
export class RangeBusiness extends RangeService{

    constructor(
        @InjectRepository(Range)
        protected repo: Repository<Range>
    ) {super(repo);}

    async findAllByEnterprise(enterprise: number){
        return this.findMany({ where: { enterprise: { id: enterprise }, active: 1 }, order: { id: 'ASC' }, relations: { amounts: true } });
    }

    async findAll(){
        return this.findMany({ where: { active: 1 }, order: { id: 'ASC' }, relations: { amounts: true } });
    }

    async activate(uuid: string): Promise<Range> {
        return await this.changeActive(uuid, 1);
    }

    async block(uuid: string): Promise<Range> {
        return await this.changeActive(uuid, 0);
    }

    async changeActive(uuid: string, active: number): Promise<Range> {
        let entity = await this.findById(uuid);
        if(entity == null) throw new Error('Entity not found for edition');
        entity.active = active;
        return await this.repo.save(entity);
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */