import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Range } from '../entity/range.entity';
import { RangeService } from './range.service';

@Injectable()
export class RangeBusiness extends RangeService{

    constructor(
        @InjectRepository(Range)
        protected repo: Repository<Range>
    ) {super(repo);}

    async findAllByEnterprise(enterprise: number){
        return this.findMany({ where: { enterprise: { id: enterprise } }, order: { id: 'ASC' }, relations: { amounts: true } });
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */