import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { User } from './entity/user.entity';
import { UserService } from './service/user.service';
import { UserController } from './controller/user.controller';
import { UserBusiness } from './service/user.business';

@Module({
    imports: [
        TypeOrmModule.forFeature([User]),
    ],
    controllers: [
        UserController,
    ],
    providers: [
        UserService, UserBusiness
    ],
    exports: [
        UserService, UserBusiness
    ],
})
export class UserModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */