export class EmployeeDTO {
    readonly uuid: string;
    readonly name: string;
    readonly id: string;
    readonly phone: string;
    readonly salary: Number;
    readonly password: string;
    readonly state: Number;
    readonly range: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */