export class AdvanceDTO {
    readonly uuid: string;
    readonly created_date: Date;
    readonly approved_date: Date;
    readonly declined_date: Date;
    readonly value: Number;
    readonly cost: Number;
    readonly employee: string;
    readonly state: string;
    readonly use_fintech: Number;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */