import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Enterprise } from './entity/enterprise.entity';
import { EnterpriseService } from './service/enterprise.service';
import { EnterpriseController } from './controller/enterprise.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([Enterprise]),
    ],
    controllers: [
        EnterpriseController,
    ],
    providers: [
        EnterpriseService,
    ],
    exports: [
        EnterpriseService,
    ],
})
export class EnterpriseModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */