import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Bank } from '../entity/bank.entity';
import { BankDTO } from '../entity/bank.dto';

@Injectable()
export class BankService extends BasicCrudService<Bank, string, BankDTO>{

    constructor(
        @InjectRepository(Bank)
        protected repo: Repository<Bank>,
    ) {super();}

    findById(id: string): Promise<Bank>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: BankDTO): Bank{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new Bank();
        entity.name = dto.name;
        return entity;
    }

    async dataValidationBeforeCreate(dto: BankDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: Bank, dto: BankDTO): Bank{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        return entity;
    }

    async dataValidationBeforeEdit(dto: BankDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */