import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { BankMessages } from '../entity/bank_messages.entity';
import { BankMessagesDTO } from '../entity/bank_messages.dto';
import { BankMessagesService } from '../service/bank_messages.service';

@Controller('bank-messages')
@UseGuards(AuthGuard('jwt'))
export class BankMessagesController extends BasicRestController<BankMessages, string, BankMessagesDTO>{

    constructor(protected service: BankMessagesService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */