import { Module } from '@nestjs/common';
import { EnterpriseModule } from './enterprise/enterprise.module';
import { UserRolModule } from './user_rol/user_rol.module';
import { UserModule } from './user/user.module';
import { RangeModule } from './range/range.module';
import { AmountModule } from './amount/amount.module';
import { RangeAmountModule } from './range_amount/range_amount.module';
import { EmployeeModule } from './employee/employee.module';
import { AdvanceStateModule } from './advance_state/advance_state.module';
import { AdvanceModule } from './advance/advance.module';
import { AuthModule } from './auth/auth.module';
import { LoginModule } from './login/login.module';

@Module({
    imports: [
        EnterpriseModule,
        UserRolModule,
        UserModule,
        RangeModule,
        AmountModule,
        RangeAmountModule,
        EmployeeModule,
        AdvanceStateModule,
        AdvanceModule,
        AuthModule,
        LoginModule
    ],
    controllers: [
    ],
    providers: [
    ],
    exports: [
    ],
})
export class ApiModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */