import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Amount } from '../entity/amount.entity';
import { AmountDTO } from '../entity/amount.dto';
import { AmountService } from '../service/amount.service';

@Controller('amount')
@UseGuards(AuthGuard('jwt'))
export class AmountController extends BasicRestController<Amount, string, AmountDTO>{

    constructor(protected service: AmountService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */