import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { BankMessages } from './entity/bank_messages.entity';
import { BankMessagesService } from './service/bank_messages.service';
import { BankMessagesController } from './controller/bank_messages.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([BankMessages]),
    ],
    controllers: [
        BankMessagesController,
    ],
    providers: [
        BankMessagesService,
    ],
    exports: [
        BankMessagesService,
    ],
})
export class BankMessagesModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */