import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Advance } from '../entity/advance.entity';
import { AdvanceDTO } from '../entity/advance.dto';
import { AdvanceService } from '../service/advance.service';

@Controller('advance')
@UseGuards(AuthGuard('jwt'))
export class AdvanceController extends BasicRestController<Advance, string, AdvanceDTO>{

    constructor(protected service: AdvanceService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */