import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Bank } from './entity/bank.entity';
import { BankService } from './service/bank.service';
import { BankController } from './controller/bank.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([Bank]),
    ],
    controllers: [
        BankController,
    ],
    providers: [
        BankService,
    ],
    exports: [
        BankService,
    ],
})
export class BankModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */