import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { UserRol } from './entity/user_rol.entity';
import { UserRolService } from './service/user_rol.service';
import { UserRolController } from './controller/user_rol.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([UserRol]),
    ],
    controllers: [
        UserRolController,
    ],
    providers: [
        UserRolService,
    ],
    exports: [
        UserRolService,
    ],
})
export class UserRolModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */