import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Amount } from './entity/amount.entity';
import { AmountService } from './service/amount.service';
import { AmountController } from './controller/amount.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([Amount]),
    ],
    controllers: [
        AmountController,
    ],
    providers: [
        AmountService,
    ],
    exports: [
        AmountService,
    ],
})
export class AmountModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */