import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { BankAccountType } from '../entity/bank_account_type.entity';
import { BankAccountTypeDTO } from '../entity/bank_account_type.dto';

@Injectable()
export class BankAccountTypeService extends BasicCrudService<BankAccountType, string, BankAccountTypeDTO>{

    constructor(
        @InjectRepository(BankAccountType)
        protected repo: Repository<BankAccountType>,
    ) {super();}

    findById(id: string): Promise<BankAccountType>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: BankAccountTypeDTO): BankAccountType{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new BankAccountType();
        entity.name = dto.name;
        return entity;
    }

    async dataValidationBeforeCreate(dto: BankAccountTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: BankAccountType, dto: BankAccountTypeDTO): BankAccountType{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        return entity;
    }

    async dataValidationBeforeEdit(dto: BankAccountTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */