import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { Bank } from 'src/api/bank/entity/bank.entity'

@Entity({name:'bank_supported'})
export class BankSupported{

    @PrimaryColumn()
    cod: string;

    @ManyToOne(() => Bank, e => e.supporteds, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "bank" })
    bank: Bank;

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */