import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Employee } from '../entity/employee.entity';
import { EmployeeDTO } from '../entity/employee.dto';
import { EmployeeService } from '../service/employee.service';

@Controller('employee')
@UseGuards(AuthGuard('jwt'))
export class EmployeeController extends BasicRestController<Employee, string, EmployeeDTO>{

    constructor(protected service: EmployeeService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */