import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Enterprise } from '../entity/enterprise.entity';
import { EnterpriseDTO } from '../entity/enterprise.dto';

@Injectable()
export class EnterpriseService extends BasicCrudService<Enterprise, number, EnterpriseDTO>{

    constructor(
        @InjectRepository(Enterprise)
        protected repo: Repository<Enterprise>,
    ) {super();}

    findAll(): Promise<Enterprise[]> {
        return this.findMany({ order: { name: 'ASC' } });
    }

    findById(id: number): Promise<Enterprise>{
        try{
            return this.findOne({where: {id:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: EnterpriseDTO): Enterprise{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new Enterprise();
        entity.nit = dto.nit;
        entity.name = dto.name;
        entity.address = dto.address;
        return entity;
    }

    async dataValidationBeforeCreate(dto: EnterpriseDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: Enterprise, dto: EnterpriseDTO): Enterprise{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.id) throw new Error('Entity id null');

        //Assign data
        entity.nit = dto.nit ? dto.nit : entity.nit;
        entity.name = dto.name ? dto.name : entity.name;
        entity.address = dto.address ? dto.address : entity.address;
        return entity;
    }

    async dataValidationBeforeEdit(dto: EnterpriseDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */