import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { Employee } from 'src/api/employee/entity/employee.entity'
import { BankSupported } from 'src/api/bank_supported/entity/bank_supported.entity'

@Entity({name:'bank'})
export class Bank{

    @PrimaryColumn()
    cod: string;

    @Column()
    name: string;

    @OneToMany(() => Employee, e => e.bank)
    employees: Employee[];

    @OneToMany(() => BankSupported, e => e.bank)
    supporteds: BankSupported[];

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */