import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { Enterprise } from 'src/api/enterprise/entity/enterprise.entity'
import { UserRol } from 'src/api/user_rol/entity/user_rol.entity'

@Entity({name:'user'})
export class User{

    @PrimaryGeneratedColumn()
    uuid: string;

    @Column()
    name: string;

    @Column()
    email: string;

    @Column()
    login: string;

    @Column()
    password: string;

    @Column()
    active: Number;

    @ManyToOne(() => Enterprise, e => e.users, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "enterprise" })
    enterprise: Enterprise;

    @ManyToOne(() => UserRol, e => e.users, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "rol" })
    rol: UserRol;

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */