export class UserDTO {
    readonly uuid: string;
    readonly name: string;
    readonly email: string;
    readonly login: string;
    readonly password: string;
    readonly active: Number;
    readonly enterprise: number;
    readonly rol: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */