import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { Amount } from 'src/api/amount/entity/amount.entity'
import { Range } from 'src/api/range/entity/range.entity'

@Entity({name:'range_amount'})
export class RangeAmount{

    @PrimaryGeneratedColumn()
    uuid: string;

    @ManyToOne(() => Amount, e => e.ranges, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "amount" })
    amount: Amount;

    @ManyToOne(() => Range, e => e.amounts, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "range" })
    range: Range;

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */