export class RangeAmountDTO {
    readonly uuid: string;
    readonly amount: string;
    readonly range: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */