import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Bank } from '../entity/bank.entity';
import { BankDTO } from '../entity/bank.dto';
import { BankService } from '../service/bank.service';

@Controller('bank')
export class BankController extends BasicRestController<Bank, string, BankDTO>{

    constructor(protected service: BankService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */