import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { BankMessages } from '../entity/bank_messages.entity';
import { BankMessagesDTO } from '../entity/bank_messages.dto';
import { Bank } from 'src/api/bank/entity/bank.entity';

@Injectable()
export class BankMessagesService extends BasicCrudService<BankMessages, string, BankMessagesDTO>{

    constructor(
        @InjectRepository(BankMessages)
        protected repo: Repository<BankMessages>,
    ) {super();}

    findById(id: string): Promise<BankMessages>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: BankMessagesDTO): BankMessages{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new BankMessages();
        entity.cod = dto.cod;
        entity.message = dto.message;
        let bank = new Bank();
        bank.cod = dto.bank;
        entity.bank = bank;
        return entity;
    }

    async dataValidationBeforeCreate(dto: BankMessagesDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: BankMessages, dto: BankMessagesDTO): BankMessages{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.message = dto.message ? dto.message : entity.message;
        return entity;
    }

    async dataValidationBeforeEdit(dto: BankMessagesDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */