import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { User } from 'src/api/user/entity/user.entity'

@Entity({name:'user_rol'})
export class UserRol{

    @PrimaryColumn()
    cod: string;

    @Column()
    name: string;

    @OneToMany(() => User, e => e.rol)
    users: User[];

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */