import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { RangeAmount } from '../entity/range_amount.entity';
import { RangeAmountDTO } from '../entity/range_amount.dto';
import { RangeAmountService } from '../service/range_amount.service';

@Controller('range-amount')
export class RangeAmountController extends BasicRestController<RangeAmount, string, RangeAmountDTO>{

    constructor(protected service: RangeAmountService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */