import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Fintech } from '../entity/fintech.entity';
import { FintechDTO } from '../entity/fintech.dto';

@Injectable()
export class FintechService extends BasicCrudService<Fintech, string, FintechDTO>{

    constructor(
        @InjectRepository(Fintech)
        protected repo: Repository<Fintech>,
    ) {super();}

    findById(id: string): Promise<Fintech>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: FintechDTO): Fintech{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new Fintech();
        entity.name = dto.name;
        return entity;
    }

    async dataValidationBeforeCreate(dto: FintechDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: Fintech, dto: FintechDTO): Fintech{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        return entity;
    }

    async dataValidationBeforeEdit(dto: FintechDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */