import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Range } from './entity/range.entity';
import { RangeService } from './service/range.service';
import { RangeController } from './controller/range.controller';
import { RangeBusiness } from './service/range.business';

@Module({
    imports: [
        TypeOrmModule.forFeature([Range]),
    ],
    controllers: [
        RangeController,
    ],
    providers: [
        RangeService, RangeBusiness
    ],
    exports: [
        RangeService, RangeBusiness
    ],
})
export class RangeModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */